name: Publish to Test PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine pyip
        pip install -r requirements.txt

    - name: Build distribution
      run: |
        rm -rf dist/
        python -m build --sdist --wheel

    - name: Debug PyPI Publish
      run: |
        echo "PyPI Token: ${{ secrets.PYPI_API_TOKEN }}"
        echo "GitHub Actor: ${{ github.actor }}"
        echo "PyPI Repository URL: https://test.pypi.org/legacy/"

    - name: Publish to Test PyPI
      env:
        TWINE_USERNAME: ${{ github.actor }}
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload --repository testpypi --verbose dist/*
    
    - name: Run registration script
      run: python tw.py
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
